# Generated by Django 3.2.13 on 2022-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WavManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filewav',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filewav',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='filewav',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
