# Generated by Django 4.0.5 on 2022-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WavManager', '0002_auto_20220623_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='filewav',
            name='ids',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='filewav',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
