# Generated by Django 4.0.5 on 2022-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WavManager', '0003_filewav_ids_alter_filewav_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filewav',
            name='foldername',
            field=models.CharField(default='', max_length=50),
        ),
    ]
